adx_append: false
adx_appendto: false
adx_create: false
adx_delete: false
adx_entitylogicalname: product
adx_entityname: Products
adx_entitypermission_webrole:
- 4b84e25d-08da-ed11-a7c6-000d3a854be1
adx_entitypermissionid: 0200e357-08da-ed11-a7c6-000d3a854be1
adx_read: true
adx_scope: 756150000
adx_write: false
